export const work = [
  {
    id: 1,
    slug: "nexus-crm-dashboard",
    title: "Nexus CRM Dashboard",
    subtitle: "SaaS Platform",
    description: "A high-performance SaaS dashboard for managing client pipelines and deal flow with real-time analytics.",
    tags: ["SaaS Platforms"],
    techStack: ["Next.js", "TypeScript", "Node.js", "PostgreSQL", "AWS"],
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
    featured: true,
  },
  {
    id: 2,
    slug: "automated-sales-agent",
    title: "Automated Sales Agent",
    subtitle: "AI Analytics Platform",
    description: "An autonomous WhatsApp bot that qualifies inbound leads 24/7 and books calls. AI-powered insights and reporting platform for enterprises.",
    tags: ["AI & Automation"],
    techStack: ["React Native", "FastAPI", "React", "AWS", "PostgreSQL"],
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    id: 3,
    slug: "legal-rag-system",
    title: "Legal Doc RAG System",
    subtitle: "Productivity App",
    description: "Smart task management app with AI automation. Internal knowledge retrieval on 10,000+ documents.",
    tags: ["AI & Automation"],
    techStack: ["React Native", "Node.js", "MongoDB", "Firebase"],
    image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    id: 4,
    slug: "ecommerce-workflow-sync",
    title: "E-Commerce Workflow Sync",
    subtitle: "Marketing Website",
    description: "Modern marketing website for a fintech startup. Zero-touch inventory sync between Shopify and external warehouses.",
    tags: ["Web & Mobile Apps"],
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    id: 5,
    slug: "launchpad-saas-platform",
    title: "Launchpad SaaS Platform",
    subtitle: "AI Platform",
    description: "Platform to build, deploy, and monitor AI agents. Multi-tenant B2B SaaS with Stripe billing and role-based access.",
    tags: ["SaaS Platforms"],
    techStack: ["Next.js", "Python", "PostgreSQL", "Docker"],
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    id: 6,
    slug: "lead-enrichment-pipeline",
    title: "Lead Enrichment Pipeline",
    subtitle: "Integration Platform",
    description: "Automated pipeline: form fills → CRM entry → Slack alert → fully enriched profile in 30 seconds.",
    tags: ["AI & Automation"],
    techStack: ["n8n", "Node.js", "PostgreSQL", "Zapier"],
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    id: 7,
    slug: "property-search-platform",
    title: "Property Search Platform",
    subtitle: "Web App",
    description: "Next.js-powered real estate platform with map-based search, filters, and agent lead capture.",
    tags: ["Web & Mobile Apps"],
    techStack: ["Next.js", "React", "Google Maps API", "PostgreSQL"],
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
  {
    id: 8,
    slug: "revenue-intelligence-dashboard",
    title: "Revenue Intelligence Dashboard",
    subtitle: "Integration Platform",
    description: "Unified data pipeline pulling from Stripe, HubSpot, and GA into a single live executive dashboard.",
    tags: ["AI & Automation"],
    techStack: ["Python", "PostgreSQL", "Stripe", "HubSpot"],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
    featured: false,
  },
];

export const workTags = ["All Projects", "SaaS Platforms", "AI & Automation", "Web & Mobile Apps", "Integrations"];

export type WorkItem = (typeof work)[number];
